import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';

const Detail = () => {
  const router = useRouter();
  const { id } = router.query;

  const [data, setData] = useState();
  const [loading, setLoading] = useState(false);

  const getData = async () => {
    try {
      setLoading(true);
      let dataFromAPI = await fetch(`https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i=${id}`);
      let dataToJSON = await dataFromAPI.json();
      setData(await dataToJSON.drinks[0]);
      setLoading(false);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    getData();
  }, []);

  if (loading) return <p>Masih Loading Gan! :)</p>;

  return (
    <div>
      <Head>
        <title>Coctail Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {data.strDrink}
      </main>
    </div>
  );
};

export default Detail;