import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';

import Navbar from '../components/Navbar';
import Banner from '../components/Banner';
import Card from '../components/Card';
import Loading from '../components/Loading';
import Footer from '../components/Footer';

export default function Home() {
  const router = useRouter();

  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);

  const getData = async () => {
    try {
      setLoading(true);
      let dataFromAPI = await fetch('https://www.thecocktaildb.com/api/json/v1/1/search.php?f=a');
      let dataToJSON = await dataFromAPI.json();
      setData(await dataToJSON.drinks);
      setLoading(false);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    getData();
  }, []);

  useEffect(() => {
    console.log('home', data);
  }, [data]);

  const handleClick = (id) => {
    router.push(`/detail/${id}`);
  };

  if (loading) return <Loading />;

  return (
    <div>
      <Head>
        <title>Next Coctail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <Navbar />
      </nav>

      <main>
        <Banner title={'Our Menu'} />
        <div className='flex flex-row flex-wrap gap-5 justify-center my-10 px-20'>
          {data?.map((item, index) => <Card key={index} id={item.idDrink} name={item.strDrink} thumb={item.strDrinkThumb} />)}
        </div>
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
