import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';

import Navbar from '../components/Navbar';
import Banner from '../components/Banner';
import Card from '../components/Card';
import Loading from '../components/Loading';
import Footer from '../components/Footer';

export default function Home() {
  const router = useRouter();
  const b = router.query.b || 'a';

  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);

  const getData = async (b) => {
    try {
      setLoading(true);
      let dataFromAPI = await fetch(`https://www.thecocktaildb.com/api/json/v1/1/search.php?f=${b}`);
      let dataToJSON = await dataFromAPI.json();
      setData(await dataToJSON.drinks);
      setLoading(false);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    getData(b);
  }, [b]);

  const handleIndexClick = (b) => {
    router.push(`/?b=${b}`);
  };

  const indexFilter = () => {
    const component = [];
    const index = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'];

    for (let i of index) {
      if (i === 'Z') {
        component.push(
          <div key={i} className='flex'>
            <p className='cursor-pointer text-lg font-bold' onClick={() => handleIndexClick(i.toLowerCase())}>{i}</p>
          </div>
        );
      } else {
        component.push(
          <div key={i} className='flex'>
            <p className='cursor-pointer text-lg font-bold' onClick={() => handleIndexClick(i.toLowerCase())}>{i}</p>
            <span className='mx-2'>/</span>
          </div>
        );
      }
    }

    return component;
  };

  if (loading) return <Loading />;

  return (
    <div>
      <Head>
        <title>Next Coctail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <Navbar />
      </nav>

      <main>
        <Banner title={'Our Menu'} />
        <div className='flex flex-row flex-wrap gap-5 justify-center my-10 px-36'>
          {data?.map((item, index) => <Card key={index} id={item.idDrink} name={item.strDrink} thumb={item.strDrinkThumb} />)}
        </div>
        <div className='flex flex-col items-center my-5'>
          <p>Browse Drinks</p>
          <div className='flex flex-row'>
            {indexFilter()}
          </div>
        </div>
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
